class Test{
	public static void main(String args[]){
/*

	int a = 10;


		System.out.println("Value of a = " +a);
		System.out.println(a); //sop
		System.out.println(a+a);

*/	
	    
/*
	byte a = (byte)-129;
	System.out.println(a);

*/
/*
	int a = 10;  //Define and Initialize
	int a1;     //Define

	short s = (byte)a;
	System.out.println(s);
*/
/*
	float a = 10.0f;
	int f = (int)a;
	System.out.println(f);
*/
/*
	float f1 = 10.0f;
	System.out.println(f1);
*/
	
	double f1 = 10.0;
	System.out.println (f1);

		}
}